apiVersion: v1
kind: Service
metadata:
  name: discover-weekly
  namespace: discover-weekly
spec:
  type: NodePort
  selector:
    app: discover-weekly
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000