apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: discover-weekly
  labels:
    app: discover-weekly
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi