apiVersion: v1
kind: Service
metadata:
  name: discover-weekly-mysql
  namespace: discover-weekly
  labels:
    app: discover-weekly
spec:
  selector:
    app: discover-weekly
    tier: mysql
  ports:
    - port: 3306
  clusterIP: None