apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discover-weekly-mysql
  namespace: discover-weekly
  labels:
    app: discover-weekly
spec:
  serviceName: discover-weekly-mysql
  selector:
    matchLabels:
      app: discover-weekly
      tier: mysql
  template:
    metadata:
      labels:
        app: discover-weekly
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: user-name
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: user-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql